import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const jsonPlaceholderApi = createApi({
  reducerPath: "jsonPlaceholderApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `https://jsonplaceholder.typicode.com/`, // Base URL
  }),
  endpoints: (builder) => ({
    getPosts: builder.query({
      query: () => `posts?_limit={20}&_page={20}`,
    }),
    createPosts: builder.mutation({
      query: (newPost) => ({
        url: "posts",
        method: "POST",
        body: newPost,
      }),
    }),
  }),
});

// Custom Hooks -> are autogenerated
export const { useGetPostsQuery, useCreatePostsMutation } = jsonPlaceholderApi;
